#!/usr/bin/env python3
"""Generate docs/adr-index.md from ADR frontmatter (fully generated file).

Reads each adr/NNNN-*.md frontmatter (id, title, status, date, domain,
superseded_by) and emits a single markdown table. The output file is committed;
CI verifies it's in sync via `git diff --exit-code`.

Usage:
    python3 scripts/gen_adr_index.py            # write docs/adr-index.md
    python3 scripts/gen_adr_index.py --check    # exit 1 if would change (CI drift check)
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ADR_DIR = os.path.join(REPO, "adr")
OUT_PATH = os.path.join(REPO, "docs", "adr-index.md")

STATUS_ICON = {
    "accepted": "✅",
    "proposed": "🔵",
    "superseded": "⬜",
    "deprecated": "⛔",
    "rejected": "❌",
}


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    fm = {}
    for line in text[4:end].splitlines():
        m = re.match(r"^(\w+):\s*(.*)$", line)
        if m:
            fm[m.group(1)] = m.group(2).strip().strip('"')
    return fm


def load():
    rows = []
    for fn in sorted(os.listdir(ADR_DIR)):
        if not re.match(r"\d{4}-.*\.md$", fn) or fn == "README.md":
            continue
        with open(os.path.join(ADR_DIR, fn), encoding="utf-8") as f:
            fm = parse_frontmatter(f.read())
        rows.append({"fn": fn, "fm": fm})
    return rows


def render(rows):
    lines = [
        "<!-- AUTO-GENERATED by scripts/gen_adr_index.py. DO NOT EDIT BY HAND. -->",
        "<!-- To update: python3 scripts/gen_adr_index.py && git add docs/adr-index.md -->",
        "",
        "# ADR Index",
        "",
        f"> {len(rows)} Architecture Decision Records (MADR 4.0.0 format). "
        "Human-readable detail in [adr/README.md](../adr/README.md).",
        "",
        "| # | Title | Status | Date | Domain | Superseded By |",
        "|---|-------|--------|------|--------|---------------|",
    ]
    for r in rows:
        fm = r["fm"]
        num = fm.get("id", "").replace("ADR-", "")
        title = fm.get("title", "")
        status = fm.get("status", "")
        icon = STATUS_ICON.get(status, "")
        date = fm.get("date", "")
        domain = fm.get("domain", "")
        sb = fm.get("superseded_by", "—") or "—"
        link = f"[{num}](../adr/{r['fn']})"
        status_cell = f"{icon} {status}" if icon else status
        lines.append(f"| {link} | {title} | {status_cell} | {date} | {domain} | {sb} |")
    lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    adrs = load()  # scan once, reuse for render + count
    content = render(adrs)
    if check:
        try:
            existing = open(OUT_PATH, encoding="utf-8").read()
        except OSError:
            existing = ""
        if existing != content:
            print("FAIL: docs/adr-index.md is out of date. Run:")
            print("  python3 scripts/gen_adr_index.py && git add docs/adr-index.md")
            sys.exit(1)
        print("OK: docs/adr-index.md is in sync.")
        return
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {OUT_PATH} ({len(adrs)} ADRs).")


if __name__ == "__main__":
    main()
